### ISSUE TITLE
First tag

### ISSUE THREAD

**Issue by sneurlax** [ntzwrk/blockstack.ts#16]
I know you're far from first "release" but for those of us wanting to use blockstack.ts in development environments without eg. yarn, it would be good to be able to even save https://github.com/ntzwrk/blockstack.ts.git#0.0.0 or #0.0.1 -- so could you tag the current working (or an upcoming) commit?  RIght now, with packages subject to change, we are leaning towards vendoring (forking and using out own blockstack.ts, which won't be subject to arbitrary changes from upstream,) but with at least one tag we can at least continue using this package

That's it!  Thanks!

**Comment by vsund** [comment]
I'd strongly not advise to use blockstack.ts in its current state :)

I'm currently in the process of revamping the classes, exports and general structure. Also, I'm even sure that, despite the compiler reporting everything as ok, the current code doesn't work as it should.

**Comment by sneurlax** [comment]
Ahhh OK, message received.  I'll have to try something else then, but it may end up that contributing here serves everyone best.

I suppose this and the other can be closed if they annoy you.

**Comment by vsund** [comment]
I suggest to use `blockstack.js` until things here are ready for release. I plan to provide information for a migration from `blockstack.js` to `blockstack.ts`.

> I suppose this and the other can be closed if they annoy you.

Going to close this because it resolves automatically when I release the first version.  The other one is probably a real issue with the installation.

---
Would be great if you'd like to contribute some stuff 🎉 Currently the issues aren't well written for external people to take them up (because they're mostly fundamental library architecture), but I'm sure that I can find things you could help with 👍
